### ISSUE TITLE
Standard mappings

### ISSUE THREAD

**Issue by mr-martian** [mr-martian/rebabel-format#16]
We've intentionally avoided trying to have a shared vocabulary across different formats, so everyone using the tool has to specify feature mappings in order to get any output. Nonetheless, for specific pairs of formats, it should be possible to create a mapping that will work for most people most of the time, allowing them to write, for example:

```toml
[export]
mode = 'conllu'
mapping_sets = ['flextext2conllu']
```

rather than

```toml
[export]
mode = 'conllu'

[[export.mappings]]
in_feature = 'FlexText:en:segnum'
out_feature = 'conllu:sent_id'

[[export.mappings]]
# many more lines
```

Any explicit mappings should override corresponding lines in the standard mapping, which should work fine if we just load the standard one first and concatenate the lists before calling `parse_mappings`.
